version: "3.7"

services:
  loopback:
    image: node:16
    restart: unless-stopped
    env_file: .env
    user: "node"
    working_dir: /app
    command: "npm run start:dev"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"

  cockroach:
    image: cockroachdb/cockroach
    restart: unless-stopped
    command: start-single-node --insecure
    ports:
      - "8080:8080"
